### PR TITLE
alertlog changes

### PR DESCRIPTION
**Pull request by pavloos**
I am not sure if you will accept this PR as it introduces some changes which you may not want but here it is anyway

- can now parse GoldenGate logs for OGG-123 type errors
- can now parse multiple log files
- normalised paths to files passed as options to the binary
- removed "description" field from the exported metric
- removed "ignore" field as well and instead errors listed to be ignored in the config file are actually ignored and not exported
- renamed ignoreora option to ignore (as it wont be always ORA but OGG as well)
- added ogg option to config file

### CODE REVIEW

**Comment by floyd871** [comment]
Great changes you have made.  In principle i have no problems with this pr, but i need the description and ignore lables in my Grafana dashboards. 

In my opinion it is better to make it configurable in the config file.
Please add options in the file section like "description: true/false" and "showignorederrors: true/false"

**Comment by bastischubert** [comment]
@floyd871 are you going to share the grafana json for the exporter within the repo?

**Comment by floyd871** [comment]
Put some Grafana Dashbords in the "grafana" folder.

**Comment by bastischubert** [comment]
\o/ kudos @floyd871

**Pull request closed without merging**
